name: terraforminfra

on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:
      - main
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - main

jobs:
  my_first_job:
    name: terraform_plan
    runs-on: [self-hosted, Windows]
    steps:
      - name: Checkout code
        uses: actions/checkout@
        
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    
    




